// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var BaseView, _, acceptableMethods;

  _ = require('underscore');

  acceptableMethods = ['get', 'put', 'post', 'delete'];

  BaseView = (function() {
    BaseView._decoratorMethodBody = function(self, method, args, key, value) {
      var obj;
      obj = {};
      obj[key] = value;
      if (_.isEmpty(args)) {
        return method.apply(self, [obj]);
      } else {
        args['0'] = _.extend(args['0'], obj);
        return method.apply(self, args);
      }
    };

    BaseView.method = function(methodName) {
      return function(method) {
        return function() {
          var ref;
          if (!((ref = methodName.toLowerCase()) === 'get' || ref === 'put' || ref === 'patch' || ref === 'post' || ref === 'delete')) {
            throw new Error("Method name for route should be one of " + acceptableMethods + "!");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'method', methodName);
        };
      };
    };

    BaseView.path = function(path) {
      return function(method) {
        return function() {
          if (typeof path !== 'string') {
            throw new Error("'path' of the route should be a string");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'path', path);
        };
      };
    };

    BaseView.id = function(id) {
      return function(method) {
        return function() {
          if (typeof id !== 'string') {
            throw new Error("'id' of the route should be a string");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'id', id);
        };
      };
    };

    BaseView.description = function(description) {
      return function(method) {
        return function() {
          if (typeof description !== 'string') {
            throw new Error("'description' of the route should be a string");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'description', description);
        };
      };
    };

    BaseView.many = function(many) {
      return function(method) {
        return function() {
          if (typeof many !== 'boolean') {
            throw new Error("'many' attribute should be boolean");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'many', many);
        };
      };
    };

    BaseView.params = function(params) {
      return function(method) {
        return function() {
          if (typeof params !== 'object') {
            throw new Error("'params' of the routing should be an object'");
          }
          return this.constructor._decoratorMethodBody(this, method, arguments, 'params', params);
        };
      };
    };

    function BaseView(server, options) {
      this.server = server;
      this.options = options;
    }

    BaseView.prototype._getBasicConfiguration = function(arg) {
      var description, id, many, method, params, path, ref;
      ref = arg != null ? arg : {}, method = ref.method, description = ref.description, id = ref.id, path = ref.path, many = ref.many, params = ref.params;
      return {
        method: method,
        path: path,
        config: {
          description: description,
          tags: ['api', "" + this.config.tag],
          id: id,
          security: this.server.securityOptions.security,
          cors: true,
          validate: {
            headers: this.server.methods.headerValidation(),
            params: params
          },
          plugins: {
            'hapi-swagger': this.server.methods.swaggerRouteResponse(method, many)
          }
        }
      };
    };

    return BaseView;

  })();

  module.exports = BaseView;

}).call(this);
