// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var BaseView, ModelView;

  BaseView = require('./baseView');

  ModelView = require('./modelView');

  module.exports = {
    BaseView: BaseView,
    ModelView: ModelView
  };

}).call(this);
