// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var FieldRelatedSerializer, ModelSerializer, PrimaryKeyRelatedSerializer, Serializer;

  Serializer = require('./serializer');

  ModelSerializer = require('./modelSerializer');

  FieldRelatedSerializer = require('./fieldRelatedSerializer');

  PrimaryKeyRelatedSerializer = require('./primaryKeyRelatedSerializer');

  module.exports = {
    Serializer: Serializer,
    ModelSerializer: ModelSerializer,
    FieldRelatedSerializer: FieldRelatedSerializer,
    PrimaryKeyRelatedSerializer: PrimaryKeyRelatedSerializer
  };

}).call(this);
