// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var BaseField, ForeignKey, ManyToMany, ManyToOne;

  BaseField = require('./baseField');

  ForeignKey = require('./foreignKey');

  ManyToOne = require('./manyToOne');

  ManyToMany = require('./manyToMany');

  module.exports = {
    BaseField: BaseField,
    ForeignKey: ForeignKey,
    ManyToOne: ManyToOne,
    ManyToMany: ManyToMany
  };

}).call(this);
